# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlRolesum < Formula
  desc "Summarize k8s RBAC resources to specified SA, Group and User!"
  homepage "https://github.com/Ladicle/kubectl-rolesum"
  version "1.5.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-rolesum/releases/download/v1.5.5/kubectl-rolesum_darwin-amd64.tar.gz"
      sha256 "b015e72c1a1ed85bfe8dc721237e60d3b95af1e39ae9bb92e82ce5210d7443b9"

      def install
        bin.install "kubectl-rolesum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ladicle/kubectl-rolesum/releases/download/v1.5.5/kubectl-rolesum_darwin-arm64.tar.gz"
      sha256 "cea7d4221040a0df3bff30f8efb74fb7101116edca7a056690413b610bbbbac3"

      def install
        bin.install "kubectl-rolesum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ladicle/kubectl-rolesum/releases/download/v1.5.5/kubectl-rolesum_linux-arm64.tar.gz"
      sha256 "f01b2545506b1cc3e151771e4822c6ada7d64f0c6b09fe84edf4ab4d25d78f72"

      def install
        bin.install "kubectl-rolesum"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-rolesum/releases/download/v1.5.5/kubectl-rolesum_linux-amd64.tar.gz"
      sha256 "f1cbb0faf9c82033b2e883a40c027c114248cc8e472d57903296b36e796413eb"

      def install
        bin.install "kubectl-rolesum"
      end
    end
  end
end
