# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlRolesum < Formula
  desc "Summarize k8s RBAC resources to specified SA, Group and User!"
  homepage "https://github.com/Ladicle/kubectl-rolesum"
  version "1.5.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Ladicle/kubectl-rolesum/releases/download/v1.5.1/kubectl-rolesum_darwin-amd64.tar.gz"
    sha256 "7465466568ee6e07d29cf63c770b657ec520d34a618ead885aae11a22a5a4b97"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-rolesum/releases/download/v1.5.1/kubectl-rolesum_linux-amd64.tar.gz"
      sha256 "946e6d8da8ae2e186fd51c73da4633105a7da4600259e69cfff60e2db9d0a833"
    end
  end

  def install
    bin.install "kubectl-rolesum"
  end
end
