# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlRolesum < Formula
  desc "Summarize k8s RBAC resources to specified SA, Group and User!"
  homepage "https://github.com/Ladicle/kubectl-rolesum"
  version "1.5.6"
  
  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-rolesum/releases/download/v1.5.6/kubectl-rolesum_darwin-amd64.tar.gz"
      sha256 "16a526b1aac8f5b00ea465edcdfaec110cb69966ab0bccee5fee4503c54e3f52"

      def install
        bin.install "kubectl-rolesum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ladicle/kubectl-rolesum/releases/download/v1.5.6/kubectl-rolesum_darwin-arm64.tar.gz"
      sha256 "4360b53eb08a54d7a4823245ec54af6032f4f172cbfe182e1df11fe21513aa38"

      def install
        bin.install "kubectl-rolesum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ladicle/kubectl-rolesum/releases/download/v1.5.6/kubectl-rolesum_linux-arm64.tar.gz"
      sha256 "ebb38e732307385554df3efd540b724a82acd448e7179dfb17a9d06c7b5cb88a"

      def install
        bin.install "kubectl-rolesum"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-rolesum/releases/download/v1.5.6/kubectl-rolesum_linux-amd64.tar.gz"
      sha256 "6e0ad8ee845da5c2b33153b7cd08de16f5a3b355e8563d37f79c42df22e7c51d"

      def install
        bin.install "kubectl-rolesum"
      end
    end
  end
end
